---

- name: k8s
  hosts: online_k8s_node
  gather_facts: yes
  roles:
    - { role: k8s-node, Conf: "online", project: "{{online}}"}


- name: k8s_master
  hosts: k8s_master
  gather_facts: yes
  roles:
    - { role: etcd, etcd_cluster: ['10.9.72.187','10.9.77.38','10.9.73.22']}
    - { role: k8s-master, etcd_cluster: ['10.9.72.187','10.9.77.38','10.9.73.22'],dns_clusterIP: '192.168.132.1'}

- name: k8s_node
  hosts: k8s_node
  gather_facts: yes
  roles:
    - {role: k8s-node, Conf: "k8s", project: "{{k8s}}"}
    - {role: gluster,cluster: ['10.9.78.27','10.9.58.171','10.9.75.238','10.9.73.88']}