---


- name:
  yum: name={{ item }} state=present
  with_items:
   - ruby
   - ruby-devel
   - gcc-c++
   - rubygems
   - zlib-devel

- name: install ruby2.0 for centos 6
  include: centos6.yml
  when: ansible_distribution_major_version == "6"

- name: gem update
  command: gem update --system
  environment:
    http_proxy: "http://113.106.11.112:8128"
  run_once: true

- name: install json
  command: gem install json
  environment:
    http_proxy: "http://113.106.11.112:8128"
    PATH: "/usr/local/rvm/rubies/ruby-2.0.0-p648/bin/:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/bin:/root/bin"
  run_once: true

- name: install backup
  command: gem install backup
  environment:
    http_proxy: "http://113.106.11.112:8128"
    PATH: "/usr/local/rvm/rubies/ruby-2.0.0-p648/bin/:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/bin:/root/bin"
  run_once: true

- name: install whenever
  command: gem install whenever
  environment:
    http_proxy: "http://113.106.11.112:8128"
    PATH: "/usr/local/rvm/rubies/ruby-2.0.0-p648/bin/:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/bin:/usr/sbin:/usr/bin:/root/bin:/usr/local/bin:/root/bin"
  run_once: true

- name: ln -s backup
  shell: ln -s  /usr/local/rvm/rubies/ruby-2.0.0-p648/bin/* /usr/local/bin/
  ignore_errors: yes
  run_once: true
  when: ansible_distribution_major_version == "6"