---

- include: env6.yml
- include: ntp6.yml
- include: selinux.yml
- include: ulimit.yml
- include: ipv6.yml
- include: tty.yml
- include: iptables.yml
- include: swap.yml
- include: network.yml
- include: service6.yml
- include: user6.yml
- include: sshd.yml
- include: secure.yml
- include: sysctl.yml

- name:
  yum: name={{ item }} state=present
  with_items:
   - rsync
   - bind-utils
   - telnet

